export const loadingArray  = [
	"⣾",
	"⣽",
	"⣻",
	"⢿",
	"⡿",
	"⣟",
	"⣯",
	"⣷"
]

const loadingSentences = [
	"Holding our breath and counting to infinity...",
	"Summoning a team of highly trained squirrels...",
	"Locating the lost city of Atlantis...",
	"Assembling the Avengers for assistance...",
	"Brewing a fresh cup of coffee for the server...",
	"Teaching hamsters to do the heavy lifting...",
	"Harnessing the power of a thousand suns...",
	"Putting together a jigsaw puzzle with one piece missing...",
	"Feeding the unicorns with magical code...",
	"Entertaining you with elevator music...",
	"Enlisting the help of a marathon-running sloth...",
	"Sending carrier pigeons to transmit the data...",
	"Convincing the computer gremlins to work faster...",
	"Polishing the loading bar for extra shine...",
	"Summoning a wizard to cast a loading spell...",
	"Conducting a nationwide search for the missing bits...",
	"Teaching a turtle to break the land-speed record...",
	"Training monkeys to type the final lines of code...",
	"Putting on a clown wig to boost loading speed...",
	"Convincing the server hamsters to run faster...",
	"Finding the last digit of Pi...",
	"Feeding cookies to the loading bar...",
	"Dusting off the ancient loading rituals...",
	"Consulting the magic 8-ball for loading predictions...",
	"Charging the loading bar with caffeinated energy...",
	"Waking up the server hamsters from a nap...",
	"Attempting to defy the laws of physics...",
	"Riding a roller coaster of loading emotions...",
	"Enlisting the help of a pack of ninja turtles...",
	"Summoning the spirit of Chuck Norris to speed things up...",
	"Juggling ones and zeros for maximum efficiency...",
	"Training a herd of snails to sprint...",
	"Spinning up a tornado of loading progress...",
	"Convincing the loading bar it's on a game show...",
	"Setting a world record for the slowest loading time...",
	"Recruiting a team of rocket-powered penguins...",
	"Rebooting the flux capacitor for optimal loading...",
	"Unleashing the Kraken to handle the heavy lifting...",
	"Calibrating the loading bar's superpowers...",
	"Bribing the loading bar with virtual cookies...",
	"Unraveling the mysteries of the loading universe...",
	"Performing a rain dance for faster data transfer...",
	"Searching for the lost city of El Dorado while loading...",
	"Translating loading messages into dolphin language...",
	"Convincing the loading bar it's actually a race...",
	"Training a herd of turtles to break the land-speed record...",
	"Converting loading time into cosmic energy...",
	"Waking up the computer gnomes from their slumber...",
	"Turning loading into a spectator sport...",
	"Recharging the loading bar with pure awesomeness...",
	"Tickling the server to elicit faster response times...",
	"Convincing the loading bar that time is relative...",
	"Riding a snail at the speed of light...",
	"Synchronizing the loading bar with the heartbeat of the universe...",
	"Whispering motivational loading quotes to the server...",
	"Playing hide-and-seek with the final piece of data...",
	"Rebooting the internet for maximum loading power...",
	"Practicing loading yoga for optimal performance...",
	"Reeling in a big catch of loading progress...",
	"Convincing the loading bar it's a world-class sprinter...",
	"Rewriting the laws of physics to accelerate loading...",
	"Crafting loading potions in a cauldron of code...",
	"Conducting a loading symphony with binary instruments...",
	"Coaxing the server hamsters with a trail of breadcrumbs...",
	"Discovering the hidden treasure at the end of the loading rainbow...",
	"Harnessing the energy of a million memes to speed things up...",
	"Sending the loading bar on a vacation to a tropical island...",
	"Negotiating with time itself to speed up the loading process...",
	"Engaging the warp drive for faster-than-light loading...",
	"Bottling loading progress in a jar for future use...",
	"Summoning a herd of flying elephants to carry the data...",
	"Cracking secret loading codes with the power of laughter...",
	"Taking the loading bar for a walk to get some fresh air...",
	"Rewriting the loading algorithm using dancing syntax...",
	"Bringing in a team of synchronized swimmers for loading precision...",
	"Convincing the loading bar to breakdance for a speed boost...",
	"Navigating a maze of loading tunnels to find the way out...",
	"Consulting a loading guru for enlightenment and speed...",
	"Training a flock of carrier pigeons for high-speed data delivery...",
	"Cracking the loading enigma with the help of a code-cracking parrot...",
	"Whispering sweet nothings to the loading bar for motivation...",
	"Convincing the server hamsters they're in a race for cheese...",
	"Exploring the loading matrix for hidden shortcuts...",
	"Using loading progress as a bargaining chip with the universe...",
	"Consulting a loading fortune teller for glimpses of the future...",
	"Embarking on a loading adventure to the center of the digital universe...",
	"Convincing the loading bar it's an Olympic athlete in training...",
	"Unlocking the secrets of the loading universe with a magic key...",
	"Polishing the loading code to a mirror-like shine...",
	"Harnessing the power of laughter to speed up loading...",
	"Calling in a team of loading ninjas for swift progress...",
	"Convincing the loading bar it's on a fast and furious mission...",
	"Navigating the loading labyrinth with a thread of hope...",
	"Unleashing a swarm of loading bees for buzzing progress...",
	"Bribing the server hamsters with virtual acorns...",
	"Reprogramming the loading matrix for an epic loading finale..."
];
